services:
  mariadb:
    image: mariadb:latest
    container_name: film-mariadb
    environment:
      MARIADB_USER: db
      MARIADB_PASSWORD: db
      MARIADB_ROOT_PASSWORD: dbpw
      MARIADB_DATABASE: films
    ports:
      - "3308:3306"
    volumes:
      - ../working-mariadb:/var/lib/mysql