package com.alhkam.film_api.rest.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.extern.jackson.Jacksonized;

import java.time.LocalDateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
public class RatingResponseDTO {
  @Schema(description = "Autogenerated rating identifier", example = "1")
  Long id;

  @Schema(description = "Timestamp when the rating was created", example = "2026-06-28T19:30:00")
  LocalDateTime created;

  @Schema(description = "Submitted score", example = "5")
  Integer score;

  @Schema(description = "Unique identifier of the rated film", example = "101")
  Long filmId;

  @Schema(description = "Unique identifier of the user who rated", example = "42")
  Long userId;
}
